/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appSasho.capaPresentacion;

import com.mycompany.appSasho.capaLogica.DBConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author santi
 */
public class appSashoFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public appSashoFrame() throws SQLException {
        DBConnection.getConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPan_Contenedor = new javax.swing.JPanel();
        JPan_MenuPrincipal = new javax.swing.JPanel();
        JBtn_GestTurnos = new javax.swing.JPanel();
        JLb_BtnGestTurnos = new javax.swing.JLabel();
        JBtn_GestClientes = new javax.swing.JPanel();
        JLb_BtnGestClientes = new javax.swing.JLabel();
        JBtn_GestCursos = new javax.swing.JPanel();
        JLb_BtnGestCursos = new javax.swing.JLabel();
        JBtn_GestAlumnos = new javax.swing.JPanel();
        JLb_BtnGestAlumnos = new javax.swing.JLabel();
        JBtn_RecomendarCursos = new javax.swing.JPanel();
        JLb_BtnRecomendarCursos = new javax.swing.JLabel();
        JBtn_MostrarAgenda = new javax.swing.JPanel();
        JLb_BtnMostrarAgenda = new javax.swing.JLabel();
        JBtn_GenerarInforme = new javax.swing.JPanel();
        JLb_BtnGenerarInforme = new javax.swing.JLabel();
        JBtn_GestProfesores = new javax.swing.JPanel();
        JLb_BtnGestProfesores = new javax.swing.JLabel();
        JBtn_AgregarParticipantes = new javax.swing.JPanel();
        JLb_BtnAgregarParticipantes = new javax.swing.JLabel();
        JPan_Header = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPan_Contenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 255), 3));
        JPan_Contenedor.setLayout(new java.awt.CardLayout());

        JPan_MenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBtn_GestTurnos.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_GestTurnos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLb_BtnGestTurnos.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JLb_BtnGestTurnos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnGestTurnos.setText("Gestionar turnos");

        javax.swing.GroupLayout JBtn_GestTurnosLayout = new javax.swing.GroupLayout(JBtn_GestTurnos);
        JBtn_GestTurnos.setLayout(JBtn_GestTurnosLayout);
        JBtn_GestTurnosLayout.setHorizontalGroup(
            JBtn_GestTurnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GestTurnosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGestTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JBtn_GestTurnosLayout.setVerticalGroup(
            JBtn_GestTurnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GestTurnosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGestTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPan_MenuPrincipal.add(JBtn_GestTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        JBtn_GestClientes.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_GestClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLb_BtnGestClientes.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JLb_BtnGestClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnGestClientes.setText("Gestionar clientes");

        javax.swing.GroupLayout JBtn_GestClientesLayout = new javax.swing.GroupLayout(JBtn_GestClientes);
        JBtn_GestClientes.setLayout(JBtn_GestClientesLayout);
        JBtn_GestClientesLayout.setHorizontalGroup(
            JBtn_GestClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GestClientesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGestClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JBtn_GestClientesLayout.setVerticalGroup(
            JBtn_GestClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GestClientesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGestClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPan_MenuPrincipal.add(JBtn_GestClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        JBtn_GestCursos.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_GestCursos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLb_BtnGestCursos.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JLb_BtnGestCursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnGestCursos.setText("Gestionar cursos");

        javax.swing.GroupLayout JBtn_GestCursosLayout = new javax.swing.GroupLayout(JBtn_GestCursos);
        JBtn_GestCursos.setLayout(JBtn_GestCursosLayout);
        JBtn_GestCursosLayout.setHorizontalGroup(
            JBtn_GestCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GestCursosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGestCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JBtn_GestCursosLayout.setVerticalGroup(
            JBtn_GestCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GestCursosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGestCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPan_MenuPrincipal.add(JBtn_GestCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        JBtn_GestAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_GestAlumnos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLb_BtnGestAlumnos.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JLb_BtnGestAlumnos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnGestAlumnos.setText("Gestionar alumnos");

        javax.swing.GroupLayout JBtn_GestAlumnosLayout = new javax.swing.GroupLayout(JBtn_GestAlumnos);
        JBtn_GestAlumnos.setLayout(JBtn_GestAlumnosLayout);
        JBtn_GestAlumnosLayout.setHorizontalGroup(
            JBtn_GestAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GestAlumnosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGestAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JBtn_GestAlumnosLayout.setVerticalGroup(
            JBtn_GestAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GestAlumnosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGestAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPan_MenuPrincipal.add(JBtn_GestAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        JBtn_RecomendarCursos.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_RecomendarCursos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLb_BtnRecomendarCursos.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JLb_BtnRecomendarCursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnRecomendarCursos.setText("Recomendar Cursos");

        javax.swing.GroupLayout JBtn_RecomendarCursosLayout = new javax.swing.GroupLayout(JBtn_RecomendarCursos);
        JBtn_RecomendarCursos.setLayout(JBtn_RecomendarCursosLayout);
        JBtn_RecomendarCursosLayout.setHorizontalGroup(
            JBtn_RecomendarCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_RecomendarCursosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnRecomendarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JBtn_RecomendarCursosLayout.setVerticalGroup(
            JBtn_RecomendarCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_RecomendarCursosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnRecomendarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPan_MenuPrincipal.add(JBtn_RecomendarCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        JBtn_MostrarAgenda.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_MostrarAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLb_BtnMostrarAgenda.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JLb_BtnMostrarAgenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnMostrarAgenda.setText("Gestionar profesores");

        javax.swing.GroupLayout JBtn_MostrarAgendaLayout = new javax.swing.GroupLayout(JBtn_MostrarAgenda);
        JBtn_MostrarAgenda.setLayout(JBtn_MostrarAgendaLayout);
        JBtn_MostrarAgendaLayout.setHorizontalGroup(
            JBtn_MostrarAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_MostrarAgendaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnMostrarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JBtn_MostrarAgendaLayout.setVerticalGroup(
            JBtn_MostrarAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_MostrarAgendaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnMostrarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPan_MenuPrincipal.add(JBtn_MostrarAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        JBtn_GenerarInforme.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_GenerarInforme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLb_BtnGenerarInforme.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JLb_BtnGenerarInforme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnGenerarInforme.setText("Generar informe");

        javax.swing.GroupLayout JBtn_GenerarInformeLayout = new javax.swing.GroupLayout(JBtn_GenerarInforme);
        JBtn_GenerarInforme.setLayout(JBtn_GenerarInformeLayout);
        JBtn_GenerarInformeLayout.setHorizontalGroup(
            JBtn_GenerarInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GenerarInformeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JBtn_GenerarInformeLayout.setVerticalGroup(
            JBtn_GenerarInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GenerarInformeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPan_MenuPrincipal.add(JBtn_GenerarInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        JBtn_GestProfesores.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_GestProfesores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLb_BtnGestProfesores.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JLb_BtnGestProfesores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnGestProfesores.setText("Gestionar profesores");

        javax.swing.GroupLayout JBtn_GestProfesoresLayout = new javax.swing.GroupLayout(JBtn_GestProfesores);
        JBtn_GestProfesores.setLayout(JBtn_GestProfesoresLayout);
        JBtn_GestProfesoresLayout.setHorizontalGroup(
            JBtn_GestProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GestProfesoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGestProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JBtn_GestProfesoresLayout.setVerticalGroup(
            JBtn_GestProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_GestProfesoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnGestProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPan_MenuPrincipal.add(JBtn_GestProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        JBtn_AgregarParticipantes.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_AgregarParticipantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLb_BtnAgregarParticipantes.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JLb_BtnAgregarParticipantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnAgregarParticipantes.setText("Agregar participantes \na curso");

        javax.swing.GroupLayout JBtn_AgregarParticipantesLayout = new javax.swing.GroupLayout(JBtn_AgregarParticipantes);
        JBtn_AgregarParticipantes.setLayout(JBtn_AgregarParticipantesLayout);
        JBtn_AgregarParticipantesLayout.setHorizontalGroup(
            JBtn_AgregarParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_AgregarParticipantesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnAgregarParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JBtn_AgregarParticipantesLayout.setVerticalGroup(
            JBtn_AgregarParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBtn_AgregarParticipantesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLb_BtnAgregarParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPan_MenuPrincipal.add(JBtn_AgregarParticipantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        JPan_Contenedor.add(JPan_MenuPrincipal, "card2");

        getContentPane().add(JPan_Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 640, 410));

        JPan_Header.setBackground(new java.awt.Color(255, 153, 51));
        JPan_Header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 255), 3));

        javax.swing.GroupLayout JPan_HeaderLayout = new javax.swing.GroupLayout(JPan_Header);
        JPan_Header.setLayout(JPan_HeaderLayout);
        JPan_HeaderLayout.setHorizontalGroup(
            JPan_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        JPan_HeaderLayout.setVerticalGroup(
            JPan_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        getContentPane().add(JPan_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appSashoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appSashoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appSashoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appSashoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new appSashoFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(appSashoFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JBtn_AgregarParticipantes;
    private javax.swing.JPanel JBtn_GenerarInforme;
    private javax.swing.JPanel JBtn_GestAlumnos;
    private javax.swing.JPanel JBtn_GestClientes;
    private javax.swing.JPanel JBtn_GestCursos;
    private javax.swing.JPanel JBtn_GestProfesores;
    private javax.swing.JPanel JBtn_GestTurnos;
    private javax.swing.JPanel JBtn_MostrarAgenda;
    private javax.swing.JPanel JBtn_RecomendarCursos;
    private javax.swing.JLabel JLb_BtnAgregarParticipantes;
    private javax.swing.JLabel JLb_BtnGenerarInforme;
    private javax.swing.JLabel JLb_BtnGestAlumnos;
    private javax.swing.JLabel JLb_BtnGestClientes;
    private javax.swing.JLabel JLb_BtnGestCursos;
    private javax.swing.JLabel JLb_BtnGestProfesores;
    private javax.swing.JLabel JLb_BtnGestTurnos;
    private javax.swing.JLabel JLb_BtnMostrarAgenda;
    private javax.swing.JLabel JLb_BtnRecomendarCursos;
    private javax.swing.JPanel JPan_Contenedor;
    private javax.swing.JPanel JPan_Header;
    private javax.swing.JPanel JPan_MenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
